version: "3.9"

services:
  client:
    build: ./client
    command: sh -c 'npm run dev'
    ports:
      - "5173:5173"
    depends_on:
      - server
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/package-lock.json

  server:
    build: ./server
    command: sh -c 'npm run migrate && npm run seed && npm run dev'
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
      - ACCESS_SECRET=hG4DPTV3Eyei5955EBG4CXzegwyqWrzLaBElfLrdTp0LCVdhkQXba6q9iqGOEzbD
    depends_on:
      - db
    networks:
      - app-network
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
        - action: rebuild
          path: ./server/package.json
        - action: rebuild
          path: ./server/package-lock.json

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
