version: "3.9"

services:
  client:
    build: ./client

    ports:
      - "5173:3000"
    depends_on:
      - server
    networks:
      - app-network
  server:
    build: ./server
    command: sh -c 'npm run migrate && npm run seed && npm run start'
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:
networks:
  app-network:
    driver: bridge
